namespace: microservices
app:
  env: dev
  replicaCount: 1
  image:
    repository: ghcr.io/mohamedsamirspot/microservices-app
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  annotations:
    reloader.stakater.com/auto: "true"

hpa:
  enabled: false

configmap:
  name: my-config
  data:
    APP_ENV: "dev"
    LOG_LEVEL: "info"
    FEATURE_FLAG: "true"

secret:
  name: my-secret
