apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-rollout-manager-role
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - deployments/status
