apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rollout-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: gitlab-rollout-manager
type: kubernetes.io/service-account-token