name: release-tag-then-call-ci

on:
  push:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.release.outputs.new_tag }}

    steps:
      - name: Run release action
        id: release
        uses: mohamedsamirspot/Microservices-Github-Actions/.github/actions/release-tag@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-ci:
    needs: release-tag
    if: needs.release-tag.outputs.new_tag != ''
    uses: ./.github/workflows/ci.yml
    with:
      tag: ${{ needs.release-tag.outputs.new_tag }}
    secrets: inherit
